// <auto-generated />
using System;
using AlarmSystem.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AlarmSystem.Core.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AlarmSystem.Core.Models.Action", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActionTask")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("AlarmSystem.Core.Models.AlarmObject", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ObjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ObjectOwnerID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ObjectOwnerID");

                    b.ToTable("AlarmObjects");
                });

            modelBuilder.Entity("AlarmSystem.Core.Models.AlarmScenerio", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AlarmSystemID")
                        .HasColumnType("int");

                    b.Property<string>("ScenerioName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AlarmSystemID");

                    b.ToTable("AlarmScenerios");
                });

            modelBuilder.Entity("AlarmSystem.Core.Models.AlarmSystem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AlarmObjectID")
                        .HasColumnType("int");

                    b.Property<string>("SystemName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AlarmObjectID");

                    b.ToTable("AlarmSystems");
                });

            modelBuilder.Entity("AlarmSystem.Core.Models.AlarmZone", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AlarmSystemID")
                        .HasColumnType("int");

                    b.Property<string>("ZoneName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AlarmSystemID");

                    b.ToTable("AlarmZones");
                });

            modelBuilder.Entity("AlarmSystem.Core.Models.IOInAlarmZone", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AlarmZoneID")
                        .HasColumnType("int");

                    b.Property<int?>("InputOutputID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AlarmZoneID");

                    b.HasIndex("InputOutputID");

                    b.ToTable("IOInAlarmZones");
                });

            modelBuilder.Entity("AlarmSystem.Core.Models.InputOutput", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AlarmSystemID")
                        .HasColumnType("int");

                    b.Property<string>("IOName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IOPlace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AlarmSystemID");

                    b.ToTable("InputOutputs");
                });

            modelBuilder.Entity("AlarmSystem.Core.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AlarmSystem.Core.Models.AlarmObject", b =>
                {
                    b.HasOne("AlarmSystem.Core.Models.User", "ObjectOwner")
                        .WithMany()
                        .HasForeignKey("ObjectOwnerID");
                });

            modelBuilder.Entity("AlarmSystem.Core.Models.AlarmScenerio", b =>
                {
                    b.HasOne("AlarmSystem.Core.Models.AlarmSystem", "AlarmSystem")
                        .WithMany()
                        .HasForeignKey("AlarmSystemID");
                });

            modelBuilder.Entity("AlarmSystem.Core.Models.AlarmSystem", b =>
                {
                    b.HasOne("AlarmSystem.Core.Models.AlarmObject", "AlarmObject")
                        .WithMany()
                        .HasForeignKey("AlarmObjectID");
                });

            modelBuilder.Entity("AlarmSystem.Core.Models.AlarmZone", b =>
                {
                    b.HasOne("AlarmSystem.Core.Models.AlarmSystem", "AlarmSystem")
                        .WithMany()
                        .HasForeignKey("AlarmSystemID");
                });

            modelBuilder.Entity("AlarmSystem.Core.Models.IOInAlarmZone", b =>
                {
                    b.HasOne("AlarmSystem.Core.Models.AlarmZone", "AlarmZone")
                        .WithMany()
                        .HasForeignKey("AlarmZoneID");

                    b.HasOne("AlarmSystem.Core.Models.InputOutput", "InputOutput")
                        .WithMany()
                        .HasForeignKey("InputOutputID");
                });

            modelBuilder.Entity("AlarmSystem.Core.Models.InputOutput", b =>
                {
                    b.HasOne("AlarmSystem.Core.Models.AlarmSystem", "AlarmSystem")
                        .WithMany()
                        .HasForeignKey("AlarmSystemID");
                });
#pragma warning restore 612, 618
        }
    }
}
